--[[
    Decursive (v 2.0) add-on for World of Warcraft UI
    Copyright (C) 2006-2007 John Wellesz (Archarodim) ( http://www.2072productions.com/?to=decursive.php )
    This is the continued work of the original Decursive (v1.9.4) by Quu
    Decursive 1.9.4 is in public domain ( www.quutar.com )

    License:
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
--]]
-------------------------------------------------------------------------------
Dcr:SetDateAndRevision("$Date$", "$Revision$");


-- Acelocal register for zhCN // {{{
local L = Dcr.L;
local LOC = Dcr.LOC;
L:RegisterTranslations("zhCN", function() return {

    [LOC.DISEASE]	=	"疾病",
    [LOC.MAGIC]	=	"魔法",
    [LOC.POISON]	=	"中毒",
    [LOC.CURSE]	=	"诅咒",
    [LOC.MAGICCHARMED]=	LOC.MAGICCHARMED,
    [LOC.CHARMED]	=	"魅惑",

    [LOC.CLASS_DRUID]	=	"德鲁伊",
    [LOC.CLASS_HUNTER]	=	"猎人",
    [LOC.CLASS_MAGE]	=	"法师",
    [LOC.CLASS_PALADIN]	=	"圣骑士",
    [LOC.CLASS_PRIEST]	=	"牧师",
    [LOC.CLASS_ROGUE]	=	"盗贼",
    [LOC.CLASS_SHAMAN]	=	"萨满祭司",
    [LOC.CLASS_WARLOCK]	=	"术士",
    [LOC.CLASS_WARRIOR]	=	"战士",

    [LOC.STR_OTHER]		=	LOC.STR_OTHER,
    [LOC.STR_OPTIONS]	=	LOC.STR_OPTIONS,
    [LOC.STR_CLOSE]		=	LOC.STR_CLOSE,
    [LOC.STR_DCR_PRIO]	=	LOC.STR_DCR_PRIO,
    [LOC.STR_DCR_SKIP]	=	LOC.STR_DCR_SKIP,
    [LOC.STR_QUICK_POP]	=	LOC.STR_QUICK_POP,
    [LOC.STR_POP]		=	LOC.STR_POP,
    [LOC.STR_GROUP]		=	LOC.STR_GROUP,

    [LOC.PRIORITY_SHOW]	=	LOC.PRIORITY_SHOW,
    [LOC.POPULATE]		=	LOC.POPULATE,
    [LOC.SKIP_SHOW]		=	LOC.SKIP_SHOW,
    [LOC.CLEAR_PRIO]	=	LOC.CLEAR_PRIO,
    [LOC.CLEAR_SKIP]	=	LOC.CLEAR_SKIP,

    [LOC.PET_FEL_CAST]	=	LOC.PET_FEL_CAST,
    [LOC.PET_DOOM_CAST]	=	LOC.PET_DOOM_CAST,

    [LOC.SPELL_POLYMORPH]		=	"变形术",
    [LOC.SPELL_CURE_DISEASE]	=	"祛病术",
    [LOC.SPELL_ABOLISH_DISEASE]	=	"驱除疾病",
    [LOC.SPELL_PURIFY]		=	"纯净术",
    [LOC.SPELL_CLEANSE]		=	"清洁术",
    [LOC.SPELL_DISPELL_MAGIC]	=	"驱散魔法",
    [LOC.SPELL_CURE_POISON]		=	"消毒术",
    [LOC.SPELL_ABOLISH_POISON]	=	"驱毒术",
    [LOC.SPELL_REMOVE_LESSER_CURSE]	=	"解除次级诅咒",
    [LOC.SPELL_REMOVE_CURSE]	=	"解除诅咒",
    [LOC.SPELL_PURGE]		=	"净化术",

    [BINDING_NAME_DCRSHOW]	=	BINDING_NAME_DCRSHOW,
    
    [BINDING_NAME_DCRMUFSHOWHIDE] =	BINDING_NAME_DCRMUFSHOWHIDE,

    [BINDING_NAME_DCRPRADD]	=	BINDING_NAME_DCRPRADD,
    [BINDING_NAME_DCRPRCLEAR]	=	BINDING_NAME_DCRPRCLEAR,
    [BINDING_NAME_DCRPRLIST]	=	BINDING_NAME_DCRPRLIST,
    [BINDING_NAME_DCRPRSHOW]	=	BINDING_NAME_DCRPRSHOW,

    [BINDING_NAME_DCRSKADD]	=	BINDING_NAME_DCRSKADD,
    [BINDING_NAME_DCRSKCLEAR]	=	BINDING_NAME_DCRSKCLEAR,
    [BINDING_NAME_DCRSKLIST]	=	BINDING_NAME_DCRSKLIST,
    [BINDING_NAME_DCRSKSHOW]	=	BINDING_NAME_DCRSKSHOW,

    [LOC.PRIORITY_LIST]	    =	LOC.PRIORITY_LIST,
    [LOC.SKIP_LIST_STR]	    =	LOC.SKIP_LIST_STR,
    [LOC.OPTION_MENU]	    =	LOC.OPTION_MENU,
    [LOC.POPULATE_LIST]	    =	LOC.POPULATE_LIST,
    [LOC.LIST_ENTRY_ACTIONS]    =	LOC.LIST_ENTRY_ACTIONS,
    [LOC.HIDE_MAIN]		    =	LOC.HIDE_MAIN,
    [LOC.SHOW_MSG]		    =	LOC.SHOW_MSG,
    [LOC.IS_HERE_MSG]	    =	LOC.IS_HERE_MSG,

    [LOC.PRINT_CHATFRAME]	=	LOC.PRINT_CHATFRAME,
    [LOC.PRINT_CUSTOM]	=	LOC.PRINT_CUSTOM,
    [LOC.PRINT_ERRORS]	=	LOC.PRINT_ERRORS,

    [LOC.SHOW_TOOLTIP]	=	LOC.SHOW_TOOLTIP,
    [LOC.REVERSE_LIVELIST]	=	LOC.REVERSE_LIVELIST,
    [LOC.TIE_LIVELIST]	=	LOC.TIE_LIVELIST,
    [LOC.HIDE_LIVELIST]	=	LOC.HIDE_LIVELIST,

    [LOC.AMOUNT_AFFLIC]	=	LOC.AMOUNT_AFFLIC,
    [LOC.BLACK_LENGTH]	=	LOC.BLACK_LENGTH,
    [LOC.SCAN_LENGTH]	=	LOC.SCAN_LENGTH,
    [LOC.ABOLISH_CHECK]	=	LOC.ABOLISH_CHECK,
    [LOC.RANDOM_ORDER]	=	LOC.RANDOM_ORDER,
    [LOC.CURE_PETS]		=	LOC.CURE_PETS,
    [LOC.IGNORE_STEALTH]	=	LOC.IGNORE_STEALTH,
    [LOC.PLAY_SOUND]	=	LOC.PLAY_SOUND,
    [LOC.ANCHOR]		=	LOC.ANCHOR,
    [LOC.DONOT_BL_PRIO]	=	LOC.DONOT_BL_PRIO,

    [LOC.SPELL_FOUND]	=	LOC.SPELL_FOUND,

    -- spells and potions
    [LOC.DREAMLESSSLEEP]	= "无梦睡眠",
    [LOC.GDREAMLESSSLEEP]	= "强效昏睡",
    [LOC.MDREAMLESSSLEEP]	= "特效无梦睡眠",
    [LOC.ANCIENTHYSTERIA]	= "上古狂乱",
    [LOC.IGNITE]		= "点燃法力",
    [LOC.TAINTEDMIND]	= "污浊之魂",
    [LOC.MAGMASHAKLES]	= "熔岩镣铐",
    [LOC.CRIPLES]		= "残废术",
    [LOC.DUSTCLOUD]		= "尘雾之云",
    [LOC.WIDOWSEMBRACE]	= "黑女巫的拥抱",
    [LOC.CURSEOFTONGUES]	= "语言诅咒",
    [LOC.SONICBURST]	= "音爆",
    [LOC.THUNDERCLAP]	= "雷霆一击",
    [LOC.DELUSIONOFJINDO]	= "金度的欺骗",
    [LOC.MUTATINGINJECTION] = "变异注射",


    -- NEW LOCALS FOR 2.0

    [LOC.DEFAULT_MACROKEY] = "`", -- the key just beneath the escape key on a QWERTY keyboard
    [LOC.OPT_LIVELIST] = LOC.OPT_LIVELIST,
    [LOC.OPT_LIVELIST_DESC] = LOC.OPT_LIVELIST_DESC,
    [LOC.OPT_HIDELIVELIST_DESC] = LOC.OPT_HIDELIVELIST_DESC,
    [LOC.OPT_SHOWTOOLTIP_DESC] = LOC.OPT_SHOWTOOLTIP_DESC,
    [LOC.OPT_PLAYSOUND_DESC] = LOC.OPT_PLAYSOUND_DESC,
    [LOC.OPT_AMOUNT_AFFLIC_DESC] = LOC.OPT_AMOUNT_AFFLIC_DESC,
    [LOC.OPT_BLACKLENTGH_DESC] = LOC.OPT_BLACKLENTGH_DESC,
    [LOC.OPT_SCANLENGTH_DESC] = LOC.OPT_SCANLENGTH_DESC,
    [LOC.OPT_REVERSE_LIVELIST_DESC] = LOC.OPT_REVERSE_LIVELIST_DESC,
    [LOC.OPT_CREATE_VIRTUAL_DEBUFF] = LOC.OPT_CREATE_VIRTUAL_DEBUFF,
    [LOC.OPT_CREATE_VIRTUAL_DEBUFF_DESC] = LOC.OPT_CREATE_VIRTUAL_DEBUFF_DESC,
    [LOC.OPT_TIE_LIVELIST_DESC] = LOC.OPT_TIE_LIVELIST_DESC,
    [LOC.OPT_MESSAGES] = LOC.OPT_MESSAGES,
    [LOC.OPT_MESSAGES_DESC] = LOC.OPT_MESSAGES_DESC,
    [LOC.OPT_CHATFRAME_DESC] = LOC.OPT_CHATFRAME_DESC,
    [LOC.OPT_PRINT_CUSTOM_DESC] = LOC.OPT_PRINT_CUSTOM_DESC,
    [LOC.OPT_PRINT_ERRORS_DESC] = LOC.OPT_PRINT_ERRORS_DESC,
    [LOC.OPT_ANCHOR_DESC] = LOC.OPT_ANCHOR_DESC,
    [LOC.OPT_MFSETTINGS] = LOC.OPT_MFSETTINGS,
    [LOC.OPT_MFSETTINGS_DESC] = LOC.OPT_MFSETTINGS_DESC,
    [LOC.OPT_DISPLAYOPTIONS] = LOC.OPT_DISPLAYOPTIONS,
    [LOC.OPT_SHOWMFS] = LOC.OPT_SHOWMFS,
    [LOC.OPT_SHOWMFS_DESC] = LOC.OPT_SHOWMFS_DESC,
    [LOC.OPT_GROWDIRECTION] = LOC.OPT_GROWDIRECTION,
    [LOC.OPT_GROWDIRECTION_DESC] = LOC.OPT_GROWDIRECTION_DESC,
    [LOC.OPT_SHOWBORDER] =  LOC.OPT_SHOWBORDER,
    [LOC.OPT_SHOWBORDER_DESC] =  LOC.OPT_SHOWBORDER_DESC,
    [LOC.OPT_MAXMFS] = LOC.OPT_MAXMFS,
    [LOC.OPT_MAXMFS_DESC] = LOC.OPT_MAXMFS_DESC,
    [LOC.OPT_UNITPERLINES] = LOC.OPT_UNITPERLINES,
    [LOC.OPT_UNITPERLINES_DESC] = LOC.OPT_UNITPERLINES_DESC,
    [LOC.OPT_MFSCALE] = LOC.OPT_MFSCALE,
    [LOC.OPT_MFSCALE_DESC] = LOC.OPT_MFSCALE_DESC,
    [LOC.OPT_SHOWHELP] = LOC.OPT_SHOWHELP,
    [LOC.OPT_SHOWHELP_DESC] = LOC.OPT_SHOWHELP_DESC,
    [LOC.OPT_MFPERFOPT] = LOC.OPT_MFPERFOPT,
    [LOC.OPT_MFREFRESHRATE] = LOC.OPT_MFREFRESHRATE,
    [LOC.OPT_MFREFRESHRATE_DESC] = LOC.OPT_MFREFRESHRATE_DESC,
    [LOC.OPT_MFREFRESHSPEED] = LOC.OPT_MFREFRESHSPEED,
    [LOC.OPT_MFREFRESHSPEED_DESC] = LOC.OPT_MFREFRESHSPEED_DESC,
    [LOC.OPT_CURINGOPTIONS] = LOC.OPT_CURINGOPTIONS,
    [LOC.OPT_CURINGOPTIONS_DESC] = LOC.OPT_CURINGOPTIONS_DESC,
    [LOC.OPT_ABOLISHCHECK_DESC] = LOC.OPT_ABOLISHCHECK_DESC,
    [LOC.OPT_DONOTBLPRIO_DESC] = LOC.OPT_DONOTBLPRIO_DESC,
    [LOC.OPT_RANDOMORDER_DESC] = LOC.OPT_RANDOMORDER_DESC,
    [LOC.OPT_CUREPETS_DESC] = LOC.OPT_CUREPETS_DESC,
    [LOC.OPT_IGNORESTEALTHED_DESC] = LOC.OPT_IGNORESTEALTHED_DESC,
    [LOC.OPT_CURINGORDEROPTIONS] = LOC.OPT_CURINGORDEROPTIONS,
    [LOC.OPT_MAGICCHECK_DESC] = LOC.OPT_MAGICCHECK_DESC,
    [LOC.OPT_MAGICCHARMEDCHECK_DESC] = LOC.OPT_MAGICCHARMEDCHECK_DESC,
    [LOC.OPT_CHARMEDCHECK_DESC] = LOC.OPT_CHARMEDCHECK_DESC,
    [LOC.OPT_POISONCHECK_DESC] = LOC.OPT_POISONCHECK_DESC,
    [LOC.OPT_DISEASECHECK_DESC] = LOC.OPT_DISEASECHECK_DESC,
    [LOC.OPT_CURSECHECK_DESC] = LOC.OPT_CURSECHECK_DESC,
    [LOC.OPT_DEBUFFFILTER] = LOC.OPT_DEBUFFFILTER,
    [LOC.OPT_DEBUFFFILTER_DESC] = LOC.OPT_DEBUFFFILTER_DESC,
    [LOC.OPT_MACROOPTIONS] = LOC.OPT_MACROOPTIONS,
    [LOC.OPT_MACROOPTIONS_DESC] = LOC.OPT_MACROOPTIONS_DESC,
    [LOC.OPT_MACROBIND] = LOC.OPT_MACROBIND,
    [LOC.OPT_MACROBIND_DESC] = LOC.OPT_MACROBIND_DESC,
    [LOC.OPT_RESETOPTIONS] = LOC.OPT_RESETOPTIONS,
    [LOC.OPT_RESETOPTIONS_DESC] = LOC.OPT_RESETOPTIONS_DESC,
    [LOC.OPT_REMOVESKDEBCONF] = LOC.OPT_REMOVESKDEBCONF,
    [LOC.OPT_RESTPROFILECONF] = LOC.OPT_RESTPROFILECONF,
    [LOC.OPT_PROFILERESET] = LOC.OPT_PROFILERESET,
    [LOC.OPT_AFFLICTEDBYSKIPPED] = LOC.OPT_AFFLICTEDBYSKIPPED,
    [LOC.OPT_DEBCHECKEDBYDEF] = LOC.OPT_DEBCHECKEDBYDEF,
    [LOC.OPT_ALWAYSIGNORE] = LOC.OPT_ALWAYSIGNORE,
    [LOC.OPT_ALWAYSIGNORE_DESC] = LOC.OPT_ALWAYSIGNORE_DESC,
    [LOC.OPT_REMOVETHISDEBUFF] = LOC.OPT_REMOVETHISDEBUFF,
    [LOC.OPT_REMOVETHISDEBUFF_DESC] = LOC.OPT_REMOVETHISDEBUFF_DESC,
    [LOC.OPT_RESETDEBUFF] = LOC.OPT_RESETDEBUFF,
    [LOC.OPT_RESETDTDCRDEFAULT] = LOC.OPT_RESETDTDCRDEFAULT,
    [LOC.OPT_USERDEBUFF] = LOC.OPT_USERDEBUFF,
    [LOC.OPT_DEBUFFENTRY_DESC] = LOC.OPT_DEBUFFENTRY_DESC,
    [LOC.OPT_ADDDEBUFF] = LOC.OPT_ADDDEBUFF,
    [LOC.OPT_ADDDEBUFF_DESC] = LOC.OPT_ADDDEBUFF_DESC,
    [LOC.OPT_ADDDEBUFF_USAGE] = LOC.OPT_ADDDEBUFF_USAGE,
    [LOC.OPT_READDDEFAULTSD] = LOC.OPT_READDDEFAULTSD,
    [LOC.OPT_READDDEFAULTSD_DESC1] = LOC.OPT_READDDEFAULTSD_DESC1,
    [LOC.OPT_READDDEFAULTSD_DESC2] = LOC.OPT_READDDEFAULTSD_DESC2,

    [LOC.OPT_LVONLYINRANGE] = LOC.OPT_LVONLYINRANGE,
    [LOC.OPT_LVONLYINRANGE_DESC] = LOC.OPT_LVONLYINRANGE_DESC,

    [LOC.OPT_MFALPHA] = OPT_MFALPHA,
    [LOC.OPT_MFALPHA_DESC] = OPT_MFALPHA_DESC,
    
    [LOC.OPT_ADVDISP] = LOC.OPT_ADVDISP,
    [LOC.OPT_ADVDISP_DESC] = LOC.OPT_ADVDISP_DESC,
    [LOC.OPT_TIECENTERANDBORDER] = LOC.OPT_TIECENTERANDBORDER,
    [LOC.OPT_TIECENTERANDBORDER_OPT] = LOC.OPT_TIECENTERANDBORDER_OPT,
    [LOC.OPT_BORDERTRANSP] = LOC.OPT_BORDERTRANSP,
    [LOC.OPT_BORDERTRANSP_DESC] = LOC.OPT_BORDERTRANSP_DESC,
    [LOC.OPT_CENTERTRANSP] = LOC.OPT_CENTERTRANSP,
    [LOC.OPT_CENTERTRANSP_DESC] = LOC.OPT_CENTERTRANSP_DESC,
    [LOC.OPT_TIEXYSPACING] = LOC.OPT_TIEXYSPACING,
    [LOC.OPT_TIEXYSPACING_DESC] = LOC.OPT_TIEXYSPACING_DESC,
    [LOC.OPT_XSPACING] = LOC.OPT_XSPACING,
    [LOC.OPT_XSPACING_DESC] = LOC.OPT_XSPACING_DESC,
    [LOC.OPT_YSPACING] = LOC.OPT_YSPACING,
    [LOC.OPT_YSPACING_DESC] = LOC.OPT_YSPACING_DESC,


    [LOC.HLP_LL_ONCLICK_TEXT] = LOC.HLP_LL_ONCLICK_TEXT,
    [LOC.HLP_LEFTCLICK] = LOC.HLP_LEFTCLICK,
    [LOC.HLP_RIGHTCLICK] = LOC.HLP_RIGHTCLICK,
    [LOC.HLP_MIDDLECLICK] = LOC.HLP_MIDDLECLICK,

    [LOC.HLP_NOTHINGTOCURE] = LOC.HLP_NOTHINGTOCURE,
    [LOC.HLP_WRONGMBUTTON] = LOC.HLP_WRONGMBUTTON,
    [LOC.HLP_USEXBUTTONTOCURE] = LOC.HLP_USEXBUTTONTOCURE,

    [LOC.CTRL] = LOC.CTRL,
    [LOC.ALT] = LOC.ALT,
    [LOC.SHIFT] = LOC.SHIFT,
    
    [LOC.TARGETUNIT] = LOC.TARGETUNIT,
    [LOC.FOCUSUNIT]  = LOC.FOCUSUNIT,


    [LOC.ABSENT] = LOC.ABSENT,
    [LOC.TOOFAR] = LOC.TOOFAR,
    [LOC.NORMAL] = LOC.NORMAL,
    [LOC.STEALTHED] = LOC.STEALTHED,
    [LOC.BLACKLISTED] = LOC.BLACKLISTED,
    [LOC.UNITSTATUS] = LOC.UNITSTATUS,
    [LOC.AFFLICTEDBY] = LOC.AFFLICTEDBY,
    
    [LOC.SUCCESSCAST] = LOC.SUCCESSCAST,

    [LOC.HANDLEHELP] = LOC.HANDLEHELP,

    [LOC.MACROKEYALREADYMAPPED] = LOC.MACROKEYALREADYMAPPED,
    [LOC.MACROKEYMAPPINGSUCCESS] = LOC.MACROKEYMAPPINGSUCCESS,
    [LOC.MACROKEYMAPPINGFAILED] = LOC.MACROKEYMAPPINGFAILED,
    [LOC.MACROKEYNOTMAPPED] = LOC.MACROKEYNOTMAPPED,

    [LOC.OPT_NOKEYWARN] = LOC.OPT_NOKEYWARN,
    [LOC.OPT_NOKEYWARN_DESC] = LOC.OPT_NOKEYWARN_DESC,
    [LOC.NOSPELL] = LOC.NOSPELL,

} end);

-- // }}}

