name: Check and buid addon

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run luacheck
      uses: BigWigsMods/actions/luacheck@master
      with:
        args: -qo 011

    - name: Package retail
      uses: BigWigsMods/packager@master
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    - name: Package classic
      uses: BigWigsMods/packager@master
      with:
        args: -g classic
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    - name: Package wraith
      uses: BigWigsMods/packager@master
      with:
        args: -g wrath
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
